name: Build and Push Docker Image

description: Build and push a Docker image to Docker Hub

inputs:
  dockerhub_username:
    description: "Docker Hub username"
    required: true

  dockerhub_repo:
    description: "Docker Hub repository name"
    required: true

  dockerhub_token:
    description: "Docker Hub access token for authentication"
    required: true

  dockerfile:
    description: "Path to the Dockerfile"
    required: true
    default: "Dockerfile"


runs:
  using: composite
  steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ inputs.dockerhub_username }}
      password: ${{ inputs.dockerhub_token }}

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3

  - name: Build and push
    uses: docker/build-push-action@v5
    with:
      context: .
      file: ${{ inputs.dockerfile }}
      push: true
      tags: ${{ inputs.dockerhub_username }}/${{inputs.dockerhub_repo}}:${{ env.VERSION }}
